language: rust
os: linux
dist: xenial

addons:
  postgresql: "11.2"
  apt:
    packages:
      - awscli
      - postgresql-11
      - postgresql-client-11

cache: cargo

services:
  - docker
  - postgresql

git:
  depth: 1

install:
  - sudo cp /etc/postgresql/10/main/pg_hba.conf /etc/postgresql/11/main/pg_hba.conf
  - sudo systemctl restart postgresql@11-main

jobs:
  include:
    - stage: build
      name: Compilation

      env:
        - RUST_BACKTRACE=1
        - PGPORT=5433
        - DATABASE_URL=postgres://postgres@localhost:5433/event.test

      script:
        - cargo install sqlx-cli --version 0.2.0
        - cargo sqlx database create && cargo sqlx migrate run
        - cargo build

    - stage: check
      name: Format

      before_install:
        - rustup component add rustfmt

      script: cargo fmt -- --check

    - stage: check
      name: Lint

      before_install:
        - rustup component add clippy

      script: cargo clippy

    - stage: check
      name: Tests
      rust: stable

      env:
        - RUST_BACKTRACE=1
        - PGPORT=5433
        - DATABASE_URL=postgres://postgres@localhost:5433/event.test

      script:
        - cargo install sqlx-cli --version 0.2.0
        - cargo sqlx database create && cargo sqlx migrate run
        - cargo test

    - stage: deploy
      name: Docs
      install: cargo install mdbook --vers 0.3.5 --force
      script: mdbook build docs && ./deploy.init.sh && PROJECT='event' ./deploy/s3-docs.sh

stages:
  - name: build
  - name: check
  - name: deploy
    if: tag IS present

notifications:
  email: false
