language: rust
os: linux
dist: xenial

addons:
  postgresql: "11.2"
  apt:
    packages:
      - awscli
      - postgresql-11
      - postgresql-client-11

cache: cargo

services:
  - docker
  - postgresql

git:
  depth: 1

install:
  - sudo cp /etc/postgresql/10/main/pg_hba.conf /etc/postgresql/11/main/pg_hba.conf
  - sudo systemctl restart postgresql@11-main

jobs:
  include:
    - stage: general
      name: Compilation

      env:
        - RUST_BACKTRACE=1
        - PGPORT=5433
        - DATABASE_URL=postgres://postgres@localhost:5433/event.test

      script:
        - cargo install sqlx-cli --version 0.2.0
        - cargo sqlx database create && cargo sqlx migrate run
        - cargo build

    - stage: check
      name: Format

      before_install:
        - rustup component add rustfmt

      script: cargo fmt -- --check

    - stage: check
      name: Lint

      before_install:
        - rustup component add clippy

      script: cargo clippy

    - stage: check
      name: Tests
      rust: stable

      env:
        - RUST_BACKTRACE=1
        - PGPORT=5433
        - DATABASE_URL=postgres://postgres@localhost:5433/event.test

      script:
        - cargo install sqlx-cli --version 0.2.0
        - cargo sqlx database create && cargo sqlx migrate run
        - cargo test

    - stage: build
      name: Docs
      install: cargo install mdbook --vers ^0.4
      script:
        - ./deploy.init.sh
        - mdbook build docs
        - ./deploy/ci-mdbook.sh

    - stage: build
      name: Build
      script:
        - ./deploy.init.sh
        - ./deploy/ci-install-tools.sh
        - ./deploy/ci-build.sh

stages:
  - name: general
  - name: check
  - name: build
    if: branch = master AND type = push

notifications:
  email: false
