[package]
name = "event"
version = "0.2.13"
authors = ["Timofey Martynov <t.martinov@netology-group.ru>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
async-std = { version = "1.6", features = ["attributes", "unstable"] }
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
config = "0.10"
crossbeam-channel = "0.4"
diesel = { version = "1.4", features = ["postgres", "uuid", "chrono", "serde_json", "r2d2"] }
diesel-derive-enum = { version = "0.4", features = ["postgres"] }
dotenv = "0.15"
env_logger = "0.7"
futures = "0.3"
futures-channel = "0.3"
futures-util = "0.3"
http = "0.1"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
signal-hook = "0.1"
svc-agent = { version = "0.14", features = ["diesel", "queue-counter"] }
svc-authn = { version = "0.6", features = ["jose", "diesel"] }
svc-authz = "0.10"
svc-error = { version = "0.1", features = ["diesel", "r2d2", "svc-agent", "svc-authn", "svc-authz", "sentry-extension"] }
url = "2.1"
uuid = { version = "0.6", features = ["v4", "serde"] }
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = "0.2"
