[package]
name = "event"
version = "0.2.22"
authors = ["Timofey Martynov <t.martinov@netology-group.ru>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
async-std = { version = "1.6", features = ["attributes", "unstable"] }
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
config = "0.10"
crossbeam-channel = "0.4"
dotenv = "0.15"
env_logger = "0.7"
futures = "0.3"
futures-channel = "0.3"
futures-util = "0.3"
http = "0.1"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
signal-hook = "0.1"
sqlx = { version = "0.4.0-beta.1", features = ["offline", "postgres", "macros", "uuid", "chrono", "json", "bigdecimal"] }
svc-agent = { version = "0.14", features = ["sqlx", "queue-counter"] }
svc-authn = { version = "0.6", features = ["jose", "sqlx"] }
svc-authz = "0.10"
svc-error = { version = "0.1", features = ["sqlx", "svc-agent", "svc-authn", "svc-authz", "sentry-extension"] }
quaint = { version = "0.1", features = ["uuid-0_8", "chrono-0_4"] }
url = "2.1"
uuid = { version = "0.8", features = ["v4", "serde"] }
tide = "0.13.0"

[patch.crates-io]
sqlx = { git = "https://github.com/feymartynov/sqlx", branch = "patch" }
