[package]
authors = ["Timofey Martynov <t.martinov@netology-group.ru>"]
edition = "2018"
name = "event"
version = "0.2.33"

[dependencies]
anyhow = "1"
async-std = {version = "1", features = ["attributes", "unstable"]}
async-trait = "0.1"
chrono = {version = "0.4", features = ["serde"]}
config = "0.11"
crossbeam-channel = "0.4"
dotenv = "0.15"
futures = "0.3"
futures-channel = "0.3"
futures-util = "0.3"
http = "0.1"
lazy_static = "1"
quaint = {version = "0.1", features = ["uuid-0_8", "chrono-0_4"]}
rusoto_core = "0.47"
rusoto_credential = "0.47"
rusoto_s3 = "0.47"
serde = "1"
serde_derive = "1"
serde_json = "1"
signal-hook = "0.3"
slog = "2"
slog-async = "2"
slog-envlogger = "2"
slog-json = "2"
slog-serde = "1.0.0-alpha9"
sqlx = {version = "0.4", features = ["offline", "postgres", "macros", "uuid", "chrono", "json", "bigdecimal", "runtime-async-std-rustls"]}
svc-agent = {version = "0.17", features = ["sqlx", "queue-counter"]}
svc-authn = {version = "0.6", features = ["jose", "sqlx"]}
svc-authz = "=0.10"
svc-error = {version = "0.1", features = ["sqlx", "svc-agent", "svc-authn", "svc-authz", "sentry-extension"]}
tide = "0.16"
tokio = {version = "1", features = ["rt", "rt-multi-thread"]}
url = "2"
uuid = {version = "0.8", features = ["v4", "serde"]}

[dev-dependencies]
rusoto_mock = "0.47"
serial_test = "0.5"
