apiVersion: skaffold/v2beta11
kind: Config
build:
  artifacts:
    - image: cr.yandex/crp1of6bddata8ain3q5/event-migration
      docker:
        dockerfile: docker/migration.dockerfile
    - image: cr.yandex/crp1of6bddata8ain3q5/event
      docker:
        dockerfile: docker/Dockerfile
  tagPolicy:
    gitCommit: {}
  local:
    push: true
    useDockerCLI: true
    tryImportMissing: true
deploy:
  helm:
    releases:
    - name: event
      chartPath: chart
      artifactOverrides:
        app.image: cr.yandex/crp1of6bddata8ain3q5/event
        migrations.image: cr.yandex/crp1of6bddata8ain3q5/event-migration
      imageStrategy:
        helm: {}
      valuesFiles:
        - deploy/values.yaml
