apiVersion: skaffold/v2beta11
kind: Config
build:
  artifacts:
    - image: foxford/event-migration
      docker:
        dockerfile: docker/migration.dockerfile
    - image: foxford/event
      docker:
        dockerfile: docker/Dockerfile
  tagPolicy:
    gitCommit: {}
  local:
    push: true
    useDockerCLI: true
    tryImportMissing: true
deploy:
  helm:
    releases:
    - name: event
      chartPath: chart
      artifactOverrides:
        container.image: foxford/event
        container.migrations: foxford/event-migration
      imageStrategy:
        helm: {}
      valuesFiles:
        - deploy/values.yaml
