apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "event.fullname" . }}
  labels:
    {{- include "event.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "event.selectorLabels" . | nindent 6 }}
