apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "event.name" . }}-pdb
  labels:
    {{- include "event.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "event.selectorLabels" . | nindent 6 }}
