version: '3'
services:
  vernemq:
    image: netologygroup/mqtt-gateway:v0.13.0
    ports:
      - "1883:1883"
      - "8080:8080"
    environment:
      APP_AUTHN_ENABLED: 0
      APP_AUTHZ_ENABLED: 0
      APP_STAT_ENABLED: 0
      APP_AGENT_LABEL: alpha
      APP_ACCOUNT_ID: mqtt-gateway.dev.svc.example.org
  backend:
    image: netologygroup/ulms-events-api-server:1.1.12
    entrypoint: /entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - ./backend/entrypoint.sh:/entrypoint.sh
      - ./backend/dbconfig.yml:/dbconfig.yml
      - ./backend/conf.d:/etc/ulms/conf.d
    links:
      - backend_db
  backend_db:
    build:
      context: ./backend_db
    volumes:
      - ./backend_db/data:/var/lib/postgresql/data
