version: '3'
services:
  vernemq:
    image: netologygroup/mqtt-gateway:v0.13.3
    ports:
      - "1883:1883"
      - "8080:8080"
    environment:
      APP_AUTHN_ENABLED: 0
      APP_AUTHZ_ENABLED: 0
      APP_STAT_ENABLED: 0
      APP_DYNSUB_ENABLED: 1
      APP_AGENT_LABEL: alpha
      APP_ACCOUNT_ID: mqtt-gateway.dev.svc.example.org
