apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "event.fullname" . }}
  labels:
    {{- include "event.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: {{ .Values.ingress.class | quote }}
  tls:
    - hosts:
        {{- range $host := .Values.ingress.hosts }}
        - {{ $host | quote }}
        {{- end }}
      secretName: {{ .Values.tls.secretName }}
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host | quote }}
      http:
        paths:
          - path: {{ include "event.ingressPath" $ }}(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ include "event.fullname" $ }}-cluster
                port:
                  number: {{ $.Values.clusterService.ports.http }}
    {{- end }}
