---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  serviceName: {{ .Chart.Name }}-headless
  replicas: {{ pluck .Values.werf.env (index .Values.app.replicas .Values.global.org .Values.global.app) | first | default (index .Values.app.replicas .Values.global.org .Values.global.app)._default }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      annotations:
        checksum/config-app: {{ include (print $.Template.BasePath "/09-cm-app.yaml") . | sha256sum }}
      labels:
        app: {{ .Chart.Name }}
    spec:
      imagePullSecrets:
      - name: registrysecret
      containers:
      - name: event
        image: {{ .Values.werf.image.event }}
        resources:
          requests:
            cpu: {{ pluck .Values.werf.env (index .Values.app.resources.cpu .Values.global.org .Values.global.app) | first | default (index .Values.app.resources.cpu .Values.global.org .Values.global.app)._default }}
            memory: {{ pluck .Values.werf.env (index .Values.app.resources.memory .Values.global.org .Values.global.app) | first | default (index .Values.app.resources.memory .Values.global.org .Values.global.app)._default }}
          limits:
            memory: {{ pluck .Values.werf.env (index .Values.app.resources.memory .Values.global.org .Values.global.app) | first | default (index .Values.app.resources.memory .Values.global.org .Values.global.app)._default }}
        env:
{{- include "envs" . | indent 8 }}
        volumeMounts:
{{- include "volumeMounts" . | indent 8 }}
      volumes:
{{- include "volumes" . | indent 6 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-headless
spec:
  selector:
    app: {{ .Chart.Name }}
  clusterIP: None